### Numpy
 - Study note to demonstrate understandings of Numpy
 - press "shift + tab" to get help tools

In [1]:
import numpy as np

In [8]:
# One-Dimensional Array

In [2]:
list_a = [ 1, 2, 3, 4, 5 ]

In [3]:
type( list_a )

list

In [4]:
list_a = np.array( list_a )
type( list_a )

numpy.ndarray

In [5]:
list_a

array([1, 2, 3, 4, 5])

In [9]:
# Two-Dimensional Array

In [6]:
list_b = [ [ 1, 2, 3] , [ 4, 5, 6 ], [ 7, 8, 9 ]]
list_b = np.array( list_b )
type( list_b )

numpy.ndarray

In [7]:
list_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Create Numpy array from 0 to 9 (exclude 10)
list_c = np.arange( 0, 10 )
list_c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Create Numpy array from 0 to 19 where increases by 5
list_d = np.arange( 0, 20, 5 )
list_d

array([ 0,  5, 10, 15])

In [13]:
# Create Numpy array from 0 to 20 where increases by 5
list_d = np.arange( 0, 21, 5 )
list_d

array([ 0,  5, 10, 15, 20])

In [14]:
# Create Numpy array from 0 to 5 where is defined by float
list_e = np.zeros( 5 )
list_e

array([0., 0., 0., 0., 0.])

In [17]:
# Create Two-Dimensional Numpy array from 0s 5 rows by 10 columns
list_e = np.zeros( ( 5, 10 ))
list_e

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
list_f = np.ones( ( 2, 3 ))
list_f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# Provides linearly spaced numericals
np.linspace( 0, 10, 5 )

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
# Provides linearly spaced numericals
np.linspace( 0, 10, 12 )

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [21]:
# Identity Matrix
np.eye( 7 )

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [23]:
# Generate One-Dimensional array of random numbers
np.random.rand( 5 )

array([0.33508503, 0.22811682, 0.81927309, 0.6291048 , 0.36972645])

In [26]:
# Generate Two-Dimensional ( 2 by 3 ) array of random numbers
np.random.rand( 2, 3 )

array([[0.42523269, 0.91051559, 0.70547914],
       [0.83539486, 0.6161773 , 0.098376  ]])

In [30]:
# Generate One-Dimensional random array of standard normal distribution --> values closer to 0
np.random.randn( 5 )

array([-1.95558316,  1.41539094,  0.42162231, -0.919878  , -2.60061874])

In [31]:
# Generate Two-Dimensional random array of standard normal distribution --> values closer to 0
np.random.randn( 2, 3 )

array([[-1.30740363,  1.78890793, -0.03955654],
       [-1.26091035, -0.3750299 , -0.60599192]])

In [33]:
# Generate random integers between 0 to 101
np.random.randint( 0, 101, 5 )

array([86, 78, 23, 83, 58])

In [35]:
# Generate random integers between 0 to 101 in Two-Dimensional Array
np.random.randint( 0, 101, ( 4, 5 ))

array([[58, 97, 46, 78, 13],
       [14, 26, 73, 98,  3],
       [35,  4, 79, 68, 93],
       [81, 25, 75, 62, 84]])

In [37]:
# Use same random number across - particluar set of random nums
np.random.seed( 42 )
np.random.rand( 4 )

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
arr = np.arange( 0, 25 )
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
# Reshape: HAS TO BE SAME SIZE --> 5 x 5 = 25
arr.reshape( 5, 5 )

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr = np.random.randint( 0, 101, 10 )
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [48]:
# Get Max in list
ranarr.max()

99

In [49]:
# Get Min in list
ranarr.min()

2

In [50]:
# Get index of Max in list
ranarr.argmax()

5

In [51]:
# Get index of Min in list
ranarr.argmin()

7

In [53]:
# Returns type of integer
ranarr.dtype

dtype('int32')

In [55]:
# Attribute - Get Shape Info
ranarr.shape

(10,)

In [57]:
arr = arr.reshape( 5, 5 )
arr.shape

(5, 5)

In [58]:
arr = arr.reshape( 25, 1 )
arr.shape

(25, 1)